export const FETCH_SALE_NUMBERS_REQUEST = 'FETCH_SALE_NUMBERS_REQUEST';
export const FETCH_SALE_NUMBERS_SUCCESS = 'FETCH_SALE_NUMBERS_SUCCESS';
export const FETCH_SALE_NUMBERS_FAILURE = 'FETCH_SALE_NUMBERS_FAILURE';