// Get all categories
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";
export const GET_ALL_CATEGORIES_FAIL = "GET_ALL_CATEGORIES_FAIL";

// Create a new category
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAIL = "CREATE_CATEGORY_FAIL";

// Update a category
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL";

// Search categories
export const SEARCH_CATEGORIES = "SEARCH_CATEGORIES";
export const SEARCH_CATEGORIES_SUCCESS = "SEARCH_CATEGORIES_SUCCESS";
export const SEARCH_CATEGORIES_FAIL = "SEARCH_CATEGORIES_FAIL";

// Get category by ID
export const GET_CATEGORY_BY_ID = "GET_CATEGORY_BY_ID";
export const GET_CATEGORY_BY_ID_SUCCESS = "GET_CATEGORY_BY_ID_SUCCESS";
export const GET_CATEGORY_BY_ID_FAIL = "GET_CATEGORY_BY_ID_FAIL";

// Upload all documents
export const UPLOAD_ALL_DOCUMENTS = "UPLOAD_ALL_DOCUMENTS";
export const UPLOAD_ALL_DOCUMENTS_SUCCESS = "UPLOAD_ALL_DOCUMENTS_SUCCESS";
export const UPLOAD_ALL_DOCUMENTS_FAIL = "UPLOAD_ALL_DOCUMENTS_FAIL";

export const CREATE_EDIT_CATEGORY_API_STATUS =
  "CREATE_EDIT_CATEGORY_API_STATUS";
