// Get all factory types
export const GET_ALL_FACTORY_TYPES = "GET_ALL_FACTORY_TYPES";
export const GET_ALL_FACTORY_TYPES_SUCCESS = "GET_ALL_FACTORY_TYPES_SUCCESS";
export const GET_ALL_FACTORY_TYPES_FAIL = "GET_ALL_FACTORY_TYPES_FAIL";

// Create factory type
export const CREATE_FACTORY_TYPE = "CREATE_FACTORY_TYPE";
export const CREATE_FACTORY_TYPE_SUCCESS = "CREATE_FACTORY_TYPE_SUCCESS";
export const CREATE_FACTORY_TYPE_FAIL = "CREATE_FACTORY_TYPE_FAIL";

// Update factory type
export const UPDATE_FACTORY_TYPE = "UPDATE_FACTORY_TYPE";
export const UPDATE_FACTORY_TYPE_SUCCESS = "UPDATE_FACTORY_TYPE_SUCCESS";
export const UPDATE_FACTORY_TYPE_FAIL = "UPDATE_FACTORY_TYPE_FAIL";

// Search factory type
export const SEARCH_FACTORY_TYPE = "SEARCH_FACTORY_TYPE";
export const SEARCH_FACTORY_TYPE_SUCCESS = "SEARCH_FACTORY_TYPE_SUCCESS";
export const SEARCH_FACTORY_TYPE_FAIL = "SEARCH_FACTORY_TYPE_FAIL";

// Get factory type by ID
export const GET_FACTORY_TYPE_BY_ID = "GET_FACTORY_TYPE_BY_ID";
export const GET_FACTORY_TYPE_BY_ID_SUCCESS = "GET_FACTORY_TYPE_BY_ID_SUCCESS";
export const GET_FACTORY_TYPE_BY_ID_FAIL = "GET_FACTORY_TYPE_BY_ID_FAIL";

// Upload all documents
export const UPLOAD_ALL_DOCUMENTS_FACTORY_TYPE =
  "UPLOAD_ALL_DOCUMENTS_FACTORY_TYPE";
export const UPLOAD_ALL_DOCUMENTS_FACTORY_TYPE_SUCCESS =
  "UPLOAD_ALL_DOCUMENTS_FACTORY_TYPE_SUCCESS";
export const UPLOAD_ALL_DOCUMENTS_FACTORY_TYPE_FAIL =
  "UPLOAD_ALL_DOCUMENTS_FACTORY_TYPE_FAIL";

export const CREATE_EDIT_FACTORY_TYPE_API_STATUS =
  "CREATE_EDIT_FACTORY_TYPE_API_STATUS";
