// GET ALL REVENUE
export const GET_ALL_REVENUE = "GET_ALL_REVENUE";
export const GET_ALL_REVENUE_SUCCESS = "GET_ALL_REVENUE_SUCCESS";
export const GET_ALL_REVENUE_FAIL = "GET_ALL_REVENUE_FAIL";

// CREATE REVENUE
export const CREATE_REVENUE = "CREATE_REVENUE";
export const CREATE_REVENUE_SUCCESS = "CREATE_REVENUE_SUCCESS";
export const CREATE_REVENUE_FAIL = "CREATE_REVENUE_FAIL";

// UPDATE REVENUE
export const UPDATE_REVENUE = "UPDATE_REVENUE";
export const UPDATE_REVENUE_SUCCESS = "UPDATE_REVENUE_SUCCESS";
export const UPDATE_REVENUE_FAIL = "UPDATE_REVENUE_FAIL";

// SEARCH REVENUE
export const SEARCH_REVENUE = "SEARCH_REVENUE";
export const SEARCH_REVENUE_SUCCESS = "SEARCH_REVENUE_SUCCESS";
export const SEARCH_REVENUE_FAIL = "SEARCH_REVENUE_FAIL";

// GET REVENUE BY ID
export const GET_REVENUE_BY_ID = "GET_REVENUE_BY_ID";
export const GET_REVENUE_BY_ID_SUCCESS = "GET_REVENUE_BY_ID_SUCCESS";
export const GET_REVENUE_BY_ID_FAIL = "GET_REVENUE_BY_ID_FAIL";

// Upload all documents
export const UPLOAD_ALL_DOCUMENTS_REVENUE = "UPLOAD_ALL_DOCUMENTS_REVENUE";
export const UPLOAD_ALL_DOCUMENTS_REVENUE_SUCCESS =
  "UPLOAD_ALL_DOCUMENTS_REVENUE_SUCCESS";
export const UPLOAD_ALL_DOCUMENTS_REVENUE_FAIL =
  "UPLOAD_ALL_DOCUMENTS_REVENUE_FAIL";

export const CREATE_EDIT_REVENUE_API_STATUS = "CREATE_EDIT_REVENUE_API_STATUS";
