// actionTypes.js
export const FETCH_DOCUMENTS_REQUEST = 'FETCH_DOCUMENTS_REQUEST';
export const FETCH_DOCUMENTS_SUCCESS = 'FETCH_DOCUMENTS_SUCCESS';
export const FETCH_DOCUMENTS_FAILURE = 'FETCH_DOCUMENTS_FAILURE';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const GET_DOCUMENT_DETAIL_REQUEST = "GET_DOCUMENT_DETAIL_REQUEST";
export const GET_DOCUMENT_DETAIL_SUCCESS = "GET_DOCUMENT_DETAIL_SUCCESS";
export const GET_DOCUMENT_DETAIL_FAILURE = "GET_DOCUMENT_DETAIL_FAILURE";

export const POST_WAREHOUSE_USER_REQUEST = 'POST_WAREHOUSE_USER_REQUEST';
export const POST_WAREHOUSE_USER_SUCCESS = 'POST_WAREHOUSE_USER_SUCCESS';
export const POST_WAREHOUSE_USER_FAILURE = 'POST_WAREHOUSE_USER_FAILURE';

export const UPDATE_WAREHOUSE_USER_REQUEST = 'UPDATE_WAREHOUSE_USER_REQUEST';
export const UPDATE_WAREHOUSE_USER_SUCCESS = 'UPDATE_WAREHOUSE_USER_SUCCESS';
export const UPDATE_WAREHOUSE_USER_FAILURE = 'UPDATE_WAREHOUSE_USER_FAILURE';

export const FETCH_AUCTION_REQUEST = 'FETCH_AUCTION_REQUEST';
export const FETCH_AUCTION_SUCCESS = 'FETCH_AUCTION_SUCCESS';
export const FETCH_AUCTION_FAILURE = 'FETCH_AUCTION_FAILURE';

export const FETCH_STATE_REQUEST = 'FETCH_STATE_REQUEST';
export const FETCH_STATE_SUCCESS = 'FETCH_STATE_SUCCESS';
export const FETCH_STATE_FAILURE = 'FETCH_STATE_FAILURE';

export const SEARCH_USERS_REQUEST = 'SEARCH_USERS_REQUEST';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAILURE = 'SEARCH_USERS_FAILURE';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';