// Action labels for role management
export const GET_ALL_ROLES = "GET_ALL_ROLES";
export const GET_ALL_ROLES_SUCCESS = "GET_ALL_ROLES_SUCCESS";
export const GET_ALL_ROLES_FAIL = "GET_ALL_ROLES_FAIL";

export const CREATE_ROLE = "CREATE_ROLE";
export const CREATE_ROLE_SUCCESS = "CREATE_ROLE_SUCCESS";
export const CREATE_ROLE_FAIL = "CREATE_ROLE_FAIL";

export const UPDATE_ROLE = "UPDATE_ROLE";
export const UPDATE_ROLE_SUCCESS = "UPDATE_ROLE_SUCCESS";
export const UPDATE_ROLE_FAIL = "UPDATE_ROLE_FAIL";

export const SEARCH_ROLE = "SEARCH_ROLE";
export const SEARCH_ROLE_SUCCESS = "SEARCH_ROLE_SUCCESS";
export const SEARCH_ROLE_FAIL = "SEARCH_ROLE_FAIL";

export const GET_ROLE_BY_ID = "GET_ROLE_BY_ID";
export const GET_ROLE_BY_ID_SUCCESS = "GET_ROLE_BY_ID_SUCCESS";
export const GET_ROLE_BY_ID_FAIL = "GET_ROLE_BY_ID_FAIL";

// Upload all documents
export const UPLOAD_ALL_DOCUMENTS_ROLE = "UPLOAD_ALL_DOCUMENTS_ROLE";
export const UPLOAD_ALL_DOCUMENTS_ROLE_SUCCESS =
  "UPLOAD_ALL_DOCUMENTS_ROLE_SUCCESS";
export const UPLOAD_ALL_DOCUMENTS_ROLE_FAIL = "UPLOAD_ALL_DOCUMENTS_ROLE_FAIL";

export const CREATE_EDIT_ROLE_API_STATUS = "CREATE_EDIT_ROLE_API_STATUS";
