// GET ALL CHARGE LIST
export const GET_ALL_CHARGE = "GET_ALL_CHARGE";
export const GET_ALL_CHARGE_SUCCESS = "GET_ALL_CHARGE_SUCCESS";
export const GET_ALL_CHARGE_FAIL = "GET_ALL_CHARGE_FAIL";

//GET ALL CHARGE MASTER WITH STATUS.
export const GET_ALL_CHARGE_WITH_STATUS = "GET_ALL_CHARGE_WITH_STATUS";
export const GET_ALL_CHARGE_WITH_STATUS_SUCCESS = "GET_ALL_CHARGE_WITH_STATUS";
export const GET_ALL_CHARGE_WITH_STATUS_FAIL =
  "GET_ALL_CHARGE_WITH_STATUS_FAIL";

// For Creating CHARGE
export const CREATE_CHARGE = "CREATE_CHARGE";
export const CREATE_CHARGE_SUCCESS = "CREATE_CHARGE_SUCCESS";
export const CREATE_CHARGE_FAIL = "CREATE_CHARGE_FAIL";

// For Updating CHARGE Data Status
export const UPDATE_CHARGE = "UPDATE_CHARGE";
export const UPDATE_CHARGE_SUCCESS = "UPDATE_CHARGE_SUCCESS";
export const UPDATE_CHARGE_FAIL = "UPDATE_CHARGE_FAIL";

// For Searching CHARGE
export const SEARCH_CHARGE = "SEARCH_CHARGE";
export const SEARCH_CHARGE_SUCCESS = "SEARCH_CHARGE_SUCCESS";
export const SEARCH_CHARGE_FAIL = "SEARCH_CHARGE_FAIL";

// For Getting CHARGE by CHARGEId
export const GET_CHARGE_BY_ID = "GET_CHARGE_BY_ID";
export const GET_CHARGE_BY_ID_SUCCESS = "GET_CHARGE_BY_ID_SUCCESS";
export const GET_CHARGE_BY_ID_FAIL = "GET_CHARGE_BY_ID_FAIL";

// Upload all documents
export const UPLOAD_ALL_DOCUMENTS_CHARGE = "UPLOAD_ALL_DOCUMENTS_CHARGE";
export const UPLOAD_ALL_DOCUMENTS_CHARGE_SUCCESS =
  "UPLOAD_ALL_DOCUMENTS_CHARGE_SUCCESS";
export const UPLOAD_ALL_DOCUMENTS_CHARGE_FAIL =
  "UPLOAD_ALL_DOCUMENTS_CHARGE_FAIL";

export const CREATE_EDIT_CHARGE_MASTER_API_STATUS =
  "CREATE_EDIT_CHARGE_MASTER_API_STATUS";
