// Tea Type Action Types
export const GET_ALL_TEA_TYPE = "GET_ALL_TEA_TYPE";
export const GET_ALL_TEA_TYPE_SUCCESS = "GET_ALL_TEA_TYPE_SUCCESS";
export const GET_ALL_TEA_TYPE_FAIL = "GET_ALL_TEA_TYPE_FAIL";

export const CREATE_TEA_TYPE = "CREATE_TEA_TYPE";
export const CREATE_TEA_TYPE_SUCCESS = "CREATE_TEA_TYPE_SUCCESS";
export const CREATE_TEA_TYPE_FAIL = "CREATE_TEA_TYPE_FAIL";

export const UPDATE_TEA_TYPE = "UPDATE_TEA_TYPE";
export const UPDATE_TEA_TYPE_SUCCESS = "UPDATE_TEA_TYPE_SUCCESS";
export const UPDATE_TEA_TYPE_FAIL = "UPDATE_TEA_TYPE_FAIL";

export const SEARCH_TEA_TYPE = "SEARCH_TEA_TYPE";
export const SEARCH_TEA_TYPE_SUCCESS = "SEARCH_TEA_TYPE_SUCCESS";
export const SEARCH_TEA_TYPE_FAIL = "SEARCH_TEA_TYPE_FAIL";

export const GET_TEA_TYPE_BY_ID = "GET_TEA_TYPE_BY_ID";
export const GET_TEA_TYPE_BY_ID_SUCCESS = "GET_TEA_TYPE_BY_ID_SUCCESS";
export const GET_TEA_TYPE_BY_ID_FAIL = "GET_TEA_TYPE_BY_ID_FAIL";

// Upload all documents
export const UPLOAD_ALL_DOCUMENTS_TEA_TYPE = "UPLOAD_ALL_DOCUMENTS_TEA_TYPE";
export const UPLOAD_ALL_DOCUMENTS_TEA_TYPE_SUCCESS =
  "UPLOAD_ALL_DOCUMENTS_TEA_TYPE_SUCCESS";
export const UPLOAD_ALL_DOCUMENTS_TEA_TYPE_FAIL =
  "UPLOAD_ALL_DOCUMENTS_TEA_TYPE_FAIL";

export const CREATE_EDIT_TEA_TYPE_API_STATUS =
  "CREATE_EDIT_TEA_TYPE_API_STATUS";
