// GET ALL PLANTATION
export const GET_ALL_PLANTATION = "GET_ALL_PLANTATION";
export const GET_ALL_PLANTATION_SUCCESS = "GET_ALL_PLANTATION_SUCCESS";
export const GET_ALL_PLANTATION_FAIL = "GET_ALL_PLANTATION_FAIL";

// CREATE PLANTATION
export const CREATE_PLANTATION = "CREATE_PLANTATION";
export const CREATE_PLANTATION_SUCCESS = "CREATE_PLANTATION_SUCCESS";
export const CREATE_PLANTATION_FAIL = "CREATE_PLANTATION_FAIL";

// UPDATE PLANTATION
export const UPDATE_PLANTATION = "UPDATE_PLANTATION";
export const UPDATE_PLANTATION_SUCCESS = "UPDATE_PLANTATION_SUCCESS";
export const UPDATE_PLANTATION_FAIL = "UPDATE_PLANTATION_FAIL";

// SEARCH PLANTATION
export const SEARCH_PLANTATION = "SEARCH_PLANTATION";
export const SEARCH_PLANTATION_SUCCESS = "SEARCH_PLANTATION_SUCCESS";
export const SEARCH_PLANTATION_FAIL = "SEARCH_PLANTATION_FAIL";

// GET PLANTATION BY ID
export const GET_PLANTATION_BY_ID = "GET_PLANTATION_BY_ID";
export const GET_PLANTATION_BY_ID_SUCCESS = "GET_PLANTATION_BY_ID_SUCCESS";
export const GET_PLANTATION_BY_ID_FAIL = "GET_PLANTATION_BY_ID_FAIL";

// Upload all documents
export const UPLOAD_ALL_DOCUMENTS_PLANTATION =
  "UPLOAD_ALL_DOCUMENTS_PLANTATION";
export const UPLOAD_ALL_DOCUMENTS_PLANTATION_SUCCESS =
  "UPLOAD_ALL_DOCUMENTS_PLANTATION_SUCCESS";
export const UPLOAD_ALL_DOCUMENTS_PLANTATION_FAIL =
  "UPLOAD_ALL_DOCUMENTS_PLANTATION_FAIL";

export const CREATE_EDIT_PLANTATION_API_STATUS =
  "CREATE_EDIT_PLANTATION_API_STATUS";
