// GET ALL BANKAC LIST
export const GET_ALL_BANKAC = "GET_ALL_BANKAC";
export const GET_ALL_BANKAC_SUCCESS = "GET_ALL_BANKAC_SUCCESS";
export const GET_ALL_BANKAC_FAIL = "GET_ALL_BANKAC_FAIL";

//GET ALL BANKAC WITH STATUS.
export const GET_ALL_BANKAC_WITH_STATUS = "GET_ALL_BANKAC_WITH_STATUS";
export const GET_ALL_BANKAC_WITH_STATUS_SUCCESS = "GET_ALL_BANKAC_WITH_STATUS";
export const GET_ALL_BANKAC_WITH_STATUS_FAIL =
  "GET_ALL_BANKAC_WITH_STATUS_FAIL";

// For Creating BANKAC
export const CREATE_BANKAC = "CREATE_BANKAC";
export const CREATE_BANKAC_SUCCESS = "CREATE_BANKAC_SUCCESS";
export const CREATE_BANKAC_FAIL = "CREATE_BANKAC_FAIL";

// For Updating BANKAC Data Status
export const UPDATE_BANKAC = "UPDATE_BANKAC";
export const UPDATE_BANKAC_SUCCESS = "UPDATE_BANKAC_SUCCESS";
export const UPDATE_BANKAC_FAIL = "UPDATE_BANKAC_FAIL";

// For Searching BANKAC
export const SEARCH_BANKAC = "SEARCH_BANKAC";
export const SEARCH_BANKAC_SUCCESS = "SEARCH_BANKAC_SUCCESS";
export const SEARCH_BANKAC_FAIL = "SEARCH_BANKAC_FAIL";

// For Getting BANKAC by BANKACId
export const GET_BANKAC_BY_ID = "GET_BANKAC_BY_ID";
export const GET_BANKAC_BY_ID_SUCCESS = "GET_BANKAC_BY_ID_SUCCESS";
export const GET_BANKAC_BY_ID_FAIL = "GET_BANKAC_BY_ID_FAIL";

// Upload all documents
export const UPLOAD_ALL_DOCUMENTS_BANKAC = "UPLOAD_ALL_DOCUMENTS_BANKAC";
export const UPLOAD_ALL_DOCUMENTS_BANKAC_SUCCESS =
  "UPLOAD_ALL_DOCUMENTS_BANKAC_SUCCESS";
export const UPLOAD_ALL_DOCUMENTS_BANKAC_FAIL =
  "UPLOAD_ALL_DOCUMENTS_BANKAC_FAIL";

export const CREATE_EDIT_BANK_AC_DETAILS_API_STATUS =
  "CREATE_EDIT_BANK_AC_DETAILS_API_STATUS";
