export const GET_ALL_CONFIGURE_PARAMETER = "GET_ALL_CONFIGURE_PARAMETER";
export const GET_ALL_CONFIGURE_PARAMETER_SUCCESS =
  "GET_ALL_CONFIGURE_PARAMETER_SUCCESS";
export const GET_ALL_CONFIGURE_PARAMETER_FAIL =
  "GET_ALL_CONFIGURE_PARAMETER_FAIL";

// For Creating CONFIGURE_PARAMETER
export const CREATE_CONFIGURE_PARAMETER = "CREATE_CONFIGURE_PARAMETER";
export const CREATE_CONFIGURE_PARAMETER_SUCCESS =
  "CREATE_CONFIGURE_PARAMETER_SUCCESS";
export const CREATE_CONFIGURE_PARAMETER_FAIL =
  "CREATE_CONFIGURE_PARAMETER_FAIL";

// For Updating State Data Status
export const UPDATE_CONFIGURE_PARAMETER = "UPDATE_CONFIGURE_PARAMETER";
export const UPDATE_CONFIGURE_PARAMETER_SUCCESS =
  "UPDATE_CONFIGURE_PARAMETER_SUCCESS";
export const UPDATE_CONFIGURE_PARAMETER_FAIL =
  "UPDATE_CONFIGURE_PARAMETER_FAIL";

// For Getting State by stateId
export const GET_CONFIGURE_PARAMETER_BY_ID = "GET_CONFIGURE_PARAMETER_BY_ID";
export const GET_CONFIGURE_PARAMETER_BY_ID_SUCCESS =
  "GET_CONFIGURE_PARAMETER_BY_ID_SUCCESS";
export const GET_CONFIGURE_PARAMETER_BY_ID_FAIL =
  "GET_CONFIGURE_PARAMETER_BY_ID_FAIL";

// Upload all documents
export const UPLOAD_ALL_DOCUMENTS_CONFIG_PARAM =
  "UPLOAD_ALL_DOCUMENTS_CONFIG_PARAM";
export const UPLOAD_ALL_DOCUMENTS_CONFIG_PARAM_SUCCESS =
  "UPLOAD_ALL_DOCUMENTS_CONFIG_PARAM_SUCCESS";
export const UPLOAD_ALL_DOCUMENTS_CONFIG_PARAM_FAIL =
  "UPLOAD_ALL_DOCUMENTS_CONFIG_PARAM_FAIL";

export const CREATE_EDIT_CONFIGURE_PARAMETER_API_STATUS =
  "CREATE_EDIT_CONFIGURE_PARAMETER_API_STATUS";
