// GET ALL SPU LIST
export const GET_ALL_SPU = "GET_ALL_SPU";
export const GET_ALL_SPU_SUCCESS = "GET_ALL_SPU_SUCCESS";
export const GET_ALL_SPU_FAIL = "GET_ALL_SPU_FAIL";

//GET ALL SPU WITH STATUS.
export const GET_ALL_SPU_WITH_STATUS = "GET_ALL_SPU_WITH_STATUS";
export const GET_ALL_SPU_WITH_STATUS_SUCCESS = "GET_ALL_SPU_WITH_STATUS";
export const GET_ALL_SPU_WITH_STATUS_FAIL = "GET_ALL_SPU_WITH_STATUS_FAIL";

// For Creating SPU
export const CREATE_SPU = "CREATE_SPU";
export const CREATE_SPU_SUCCESS = "CREATE_SPU_SUCCESS";
export const CREATE_SPU_FAIL = "CREATE_SPU_FAIL";

// For Updating SPU Data Status
export const UPDATE_SPU = "UPDATE_SPU";
export const UPDATE_SPU_SUCCESS = "UPDATE_SPU_SUCCESS";
export const UPDATE_SPU_FAIL = "UPDATE_SPU_FAIL";

// For Searching SPU
export const SEARCH_SPU = "SEARCH_SPU";
export const SEARCH_SPU_SUCCESS = "SEARCH_SPU_SUCCESS";
export const SEARCH_SPU_FAIL = "SEARCH_SPU_FAIL";

// For Getting SPU by SPUId
export const GET_SPU_BY_ID = "GET_SPU_BY_ID";
export const GET_SPU_BY_ID_SUCCESS = "GET_SPU_BY_ID_SUCCESS";
export const GET_SPU_BY_ID_FAIL = "GET_SPU_BY_ID_FAIL";

// Upload all documents
export const UPLOAD_ALL_DOCUMENTS_SPU = "UPLOAD_ALL_DOCUMENTS_SPU";
export const UPLOAD_ALL_DOCUMENTS_SPU_SUCCESS =
  "UPLOAD_ALL_DOCUMENTS_SPU_SUCCESS";
export const UPLOAD_ALL_DOCUMENTS_SPU_FAIL = "UPLOAD_ALL_DOCUMENTS_SPU_FAIL";

export const CREATE_EDIT_SPU_API_STATUS = "CREATE_EDIT_SPU_API_STATUS";
