export const GET_ALL_CHARGE_CODE = "GET_ALL_CHARGE_CODE";
export const GET_ALL_CHARGE_CODE_SUCCESS = "GET_ALL_CHARGE_CODE_SUCCESS";
export const GET_ALL_CHARGE_CODE_FAIL = "GET_ALL_CHARGE_CODE_FAIL";

export const GET_ALL_CHARGE_CODE_WITHOUT_FILTER =
  "GET_ALL_CHARGE_CODE_WITHOUT_FILTER";
export const GET_ALL_CHARGE_CODE_WITHOUT_FILTER_SUCCESS =
  "GET_ALL_CHARGE_CODE_WITHOUT_FILTER_SUCCESS";
export const GET_ALL_CHARGE_CODE_WITHOUT_FILTER_FAIL =
  "GET_ALL_CHARGE_CODE_WITHOUT_FILTER_FAIL";

// For Creating CHARGE_CODE
export const CREATE_CHARGE_CODE = "CREATE_CHARGE_CODE";
export const CREATE_CHARGE_CODE_SUCCESS = "CREATE_CHARGE_CODE_SUCCESS";
export const CREATE_CHARGE_CODE_FAIL = "CREATE_CHARGE_CODE_FAIL";

// For Updating State Data Status
export const UPDATE_CHARGE_CODE = "UPDATE_CHARGE_CODE";
export const UPDATE_CHARGE_CODE_SUCCESS = "UPDATE_CHARGE_CODE_SUCCESS";
export const UPDATE_CHARGE_CODE_FAIL = "UPDATE_CHARGE_CODE_FAIL";

// For Getting State by stateId
export const GET_CHARGE_CODE_BY_ID = "GET_CHARGE_CODE_BY_ID";
export const GET_CHARGE_CODE_BY_ID_SUCCESS = "GET_CHARGE_CODE_BY_ID_SUCCESS";
export const GET_CHARGE_CODE_BY_ID_FAIL = "GET_CHARGE_CODE_BY_ID_FAIL";
// Upload all documents
export const UPLOAD_ALL_DOCUMENTS_CHARGE_CODE =
  "UPLOAD_ALL_DOCUMENTS_CHARGE_CODE";
export const UPLOAD_ALL_DOCUMENTS_CHARGE_CODE_SUCCESS =
  "UPLOAD_ALL_DOCUMENTS_CHARGE_CODE_SUCCESS";
export const UPLOAD_ALL_DOCUMENTS_CHARGE_CODE_FAIL =
  "UPLOAD_ALL_DOCUMENTS_CHARGE_CODE_FAIL";

export const CREATE_EDIT_CHARGE_CODE_API_STATUS =
  "CREATE_EDIT_CHARGE_CODE_API_STATUS";
