const SidebarContant = [
  {
    show: true,
    modalName: "Utility",
    title: "Master",
    content: [
      // { name: "categoryMaster", title: "Category master" },
      // { name: "manufactureMapping", title: "Manufacture Mapping" },
      // { name: "gradeMaster", title: "Grade Master" },
      // { name: "markMaster", title: "Mark Master" },
      { name: "createStateMaster", title: "Create State Master" },
      { name: "createAuctionCenter", title: "Create Auction Center" },
      { name: "createCategory", title: "Create Category" },
      { name: "createTeaType", title: "Create Tea Type" },
      { name: "createSubTeaType", title: "Create Sub Tea Type" },
      {
        name: "createPlantationDistrictMaster",
        title: "Create Plantation District Master",
      },
      {
        name: "createRevenueDistrictMaster",
        title: "Create Revenue District Master",
      },
      { name: "createGrade", title: "Create Grade" },
      { name: "createFactoryType", title: "Create Factory Type" },
      { name: "createRole", title: "Create Role" },
      { name: "chargeCode", title: "Charge Code" },
      { name: "createChargeMaster", title: "Create Charge Master" },
      { name: "createTaxMaster", title: "Create Tax Master" },
      { name: "CreateConfigureParameter", title: "Create Configure Parameter" },
      { name: "createSpuMaster", title: "Create Spu Master" },
      { name: "createBankAccountDetail", title: "Create Bank Account Detail" },
      { name: "RegisterUser", title: "Register User" },
      // {
      //   name: "WarehouseUserRegistration",
      //   title: "Warehouse User Registration",
      // },

    ],
  },
  {
    title: "Pre-Auction",
    content: [
      { name: "saleProgramMaster", title: "Sale Program master" },

      { name: "invoice", title: "Invoice" },
      { name: "awr", title: "AWR" },
      { name: "kutcha", title: "Kutcha Catalog" },
      { name: "lotnoseries", title: "Lot No Series" },
      { name: "AuctionSession", title: "Auction Session Master" },
      { name: "sampleshortage", title: "Sample & Shortage" },
      { name: "auctioncatalog", title: "Auction Catalog" },
      { name: "groupMaster", title: "Group Master" },
      { name: "maxBidEntry", title: "Max Bid Entry" },
      { name: "businessRule", title: "Business Rule" },
      { name: "preAuctionStatusReport", title: "Pre Auction Status Report" },
      { name: "teaQualityReport", title: "Tea Quality Report" },
    ],
    show: true,
    modalName: "preAuction",
  },
  // {
  //   title: "Invoice",
  //   content: "invoice",
  //   show: true,
  //   modalName: "invoice",
  // },
  {
    title: "Auction",
    content: "XXX XXX XXX",
    show: true,
    modalName: "Auction",
  },
  {
    title: "Post Auction",
    content: "XXX XXX XXX",
    show: true,
    modalName: "PostAuction",
  },
  { title: "Report", content: "XXX XXX XXX", show: true, modalName: "Report" },
  {
    title: "Miscellaneous",
    content: "XXX XXX XXX",
    show: true,
    modalName: "Miscellaneous",
  },
];
export default SidebarContant;
