 // actionTypes.js
export const FETCH_SAMPLE_SHORTAGE_LIST_REQUEST = "FETCH_SAMPLE_SHORTAGE_LIST_REQUEST";
export const FETCH_SAMPLE_SHORTAGE_LIST_SUCCESS = "FETCH_SAMPLE_SHORTAGE_LIST_SUCCESS";
export const FETCH_SAMPLE_SHORTAGE_LIST_FAILURE = "FETCH_SAMPLE_SHORTAGE_LIST_FAILURE";



// actions.js
export const FETCH_SAMPLE_SHORTAGE_ID_REQUEST = 'FETCH_SAMPLE_SHORTAGE_ID_REQUEST';
export const FETCH_SAMPLE_SHORTAGE_ID_SUCCESS = 'FETCH_SAMPLE_SHORTAGE_ID_SUCCESS';
export const FETCH_SAMPLE_SHORTAGE_ID_FAILURE = 'FETCH_SAMPLE_SHORTAGE_ID_FAILURE';



// actionTypes.js
export const CHECK_PACKAGE_REQUEST = 'CHECK_PACKAGE_REQUEST';
export const CHECK_PACKAGE_SUCCESS = 'CHECK_PACKAGE_SUCCESS';
export const CHECK_PACKAGE_FAILURE = 'CHECK_PACKAGE_FAILURE';



// actionTypes.js
export const UPLOAD_SAMPLE_SHORTAGE_REQUEST = 'UPLOAD_SAMPLE_SHORTAGE_REQUEST';
export const UPLOAD_SAMPLE_SHORTAGE_SUCCESS = 'UPLOAD_SAMPLE_SHORTAGE_SUCCESS';
export const UPLOAD_SAMPLE_SHORTAGE_FAILURE = 'UPLOAD_SAMPLE_SHORTAGE_FAILURE';



// actionTypes.js
export const UPDATE_SAMPLE_SHORTAGE_REQUEST = 'UPDATE_SAMPLE_SHORTAGE_REQUEST';
export const UPDATE_SAMPLE_SHORTAGE_SUCCESS = 'UPDATE_SAMPLE_SHORTAGE_SUCCESS';
export const UPDATE_SAMPLE_SHORTAGE_FAILURE = 'UPDATE_SAMPLE_SHORTAGE_FAILURE';
