// Define action types
export const GET_DOCUMENT_BY_ID = "GET_DOCUMENT_BY_ID";
export const GET_DOCUMENT_BY_ID_SUCCESS = "GET_DOCUMENT_BY_ID_SUCCESS";
export const GET_DOCUMENT_BY_ID_FAIL = "GET_DOCUMENT_BY_ID_FAIL";

export const GET_HISTORY_BY_ID = "GET_HISTORY_BY_ID";
export const GET_HISTORY_BY_ID_SUCCESS = "GET_HISTORY_BY_ID_SUCCESS";
export const GET_HISTORY_BY_ID_FAIL = "GET_HISTORY_BY_ID_FAIL";
