// GET ALL SUB TEA TYPES
export const GET_ALL_SUB_TEA_TYPES = "GET_ALL_SUB_TEA_TYPES";
export const GET_ALL_SUB_TEA_TYPES_SUCCESS = "GET_ALL_SUB_TEA_TYPES_SUCCESS";
export const GET_ALL_SUB_TEA_TYPES_FAIL = "GET_ALL_SUB_TEA_TYPES_FAIL";

// CREATE SUB TEA TYPE
export const CREATE_SUB_TEA_TYPE = "CREATE_SUB_TEA_TYPE";
export const CREATE_SUB_TEA_TYPE_SUCCESS = "CREATE_SUB_TEA_TYPE_SUCCESS";
export const CREATE_SUB_TEA_TYPE_FAIL = "CREATE_SUB_TEA_TYPE_FAIL";

// UPDATE SUB TEA TYPE
export const UPDATE_SUB_TEA_TYPE = "UPDATE_SUB_TEA_TYPE";
export const UPDATE_SUB_TEA_TYPE_SUCCESS = "UPDATE_SUB_TEA_TYPE_SUCCESS";
export const UPDATE_SUB_TEA_TYPE_FAIL = "UPDATE_SUB_TEA_TYPE_FAIL";

// SEARCH SUB TEA TYPE
export const SEARCH_SUB_TEA_TYPE = "SEARCH_SUB_TEA_TYPE";
export const SEARCH_SUB_TEA_TYPE_SUCCESS = "SEARCH_SUB_TEA_TYPE_SUCCESS";
export const SEARCH_SUB_TEA_TYPE_FAIL = "SEARCH_SUB_TEA_TYPE_FAIL";

// GET SUB TEA TYPE BY ID
export const GET_SUB_TEA_TYPE_BY_ID = "GET_SUB_TEA_TYPE_BY_ID";
export const GET_SUB_TEA_TYPE_BY_ID_SUCCESS = "GET_SUB_TEA_TYPE_BY_ID_SUCCESS";
export const GET_SUB_TEA_TYPE_BY_ID_FAIL = "GET_SUB_TEA_TYPE_BY_ID_FAIL";

// Upload all documents
export const UPLOAD_ALL_DOCUMENTS_SUB_TEA_TYPE =
  "UPLOAD_ALL_DOCUMENTS_SUB_TEA_TYPE";
export const UPLOAD_ALL_DOCUMENTS_SUB_TEA_TYPE_SUCCESS =
  "UPLOAD_ALL_DOCUMENTS_SUB_TEA_TYPE_SUCCESS";
export const UPLOAD_ALL_DOCUMENTS_SUB_TEA_TYPE_FAIL =
  "UPLOAD_ALL_DOCUMENTS_SUB_TEA_TYPE_FAIL";

export const CREATE_EDIT_SUB_TEA_TYPE_API_STATUS =
  "CREATE_EDIT_SUB_TEA_TYPE_API_STATUS";
