export const GET_ALL_AUCTION_CENTER = "GET_ALL_AUCTION_CENTER";
export const GET_ALL_AUCTION_CENTER_SUCCESS = "GET_ALL_AUCTION_CENTER_SUCCESS";
export const GET_ALL_AUCTION_CENTER_FAIL = "GET_ALL_AUCTION_CENTER_FAIL";

// Update Auction Center Actions
export const UPDATE_AUCTION_CENTER = "UPDATE_AUCTION_CENTER";
export const UPDATE_AUCTION_CENTER_SUCCESS = "UPDATE_AUCTION_CENTER_SUCCESS";
export const UPDATE_AUCTION_CENTER_FAIL = "UPDATE_AUCTION_CENTER_FAIL";

// Create Auction Center Actions
export const CREATE_AUCTION_CENTER = "CREATE_AUCTION_CENTER";
export const CREATE_AUCTION_CENTER_SUCCESS = "CREATE_AUCTION_CENTER_SUCCESS";
export const CREATE_AUCTION_CENTER_FAIL = "CREATE_AUCTION_CENTER_FAIL";

// Search Auction Center Actions
export const SEARCH_AUCTION_CENTER = "SEARCH_AUCTION_CENTER";
export const SEARCH_AUCTION_CENTER_SUCCESS = "SEARCH_AUCTION_CENTER_SUCCESS";
export const SEARCH_AUCTION_CENTER_FAIL = "SEARCH_AUCTION_CENTER_FAIL";

// Get Auction Center by ID Actions
export const GET_AUCTION_CENTER_BY_ID = "GET_AUCTION_CENTER_BY_ID";
export const GET_AUCTION_CENTER_BY_ID_SUCCESS =
  "GET_AUCTION_CENTER_BY_ID_SUCCESS";
export const GET_AUCTION_CENTER_BY_ID_FAIL = "GET_AUCTION_CENTER_BY_ID_FAIL";

// Upload all documents
export const UPLOAD_ALL_DOCUMENTS_AUCTION_CENTER =
  "UPLOAD_ALL_DOCUMENTS_AUCTION_CENTER";
export const UPLOAD_ALL_DOCUMENTS_AUCTION_CENTER_SUCCESS =
  "UPLOAD_ALL_DOCUMENTS_AUCTION_CENTER_SUCCESS";
export const UPLOAD_ALL_DOCUMENTS_AUCTION_CENTER_FAIL =
  "UPLOAD_ALL_DOCUMENTS_AUCTION_CENTER_FAIL";

export const CREATE_EDIT_AUCTION_CENTER_API_STATUS =
  "CREATE_EDIT_AUCTION_CENTER_API_STATUS";
