// GET ALL STATE LIST
export const GET_ALL_STATE = "GET_ALL_STATE";
export const GET_ALL_STATE_SUCCESS = "GET_ALL_STATE_SUCCESS";
export const GET_ALL_STATE_FAIL = "GET_ALL_STATE_FAIL";

// For Creating State
export const CREATE_STATE = "CREATE_STATE";
export const CREATE_STATE_SUCCESS = "CREATE_STATE_SUCCESS";
export const CREATE_STATE_FAIL = "CREATE_STATE_FAIL";

// For Updating State Data Status
export const UPDATE_STATE = "UPDATE_STATE";
export const UPDATE_STATE_SUCCESS = "UPDATE_STATE_SUCCESS";
export const UPDATE_STATE_FAIL = "UPDATE_STATE_FAIL";

// For Searching State
export const SEARCH_STATE = "SEARCH_STATE";
export const SEARCH_STATE_SUCCESS = "SEARCH_STATE_SUCCESS";
export const SEARCH_STATE_FAIL = "SEARCH_STATE_FAIL";

// For Getting State by stateId
export const GET_STATE_BY_ID = "GET_STATE_BY_ID";
export const GET_STATE_BY_ID_SUCCESS = "GET_STATE_BY_ID_SUCCESS";
export const GET_STATE_BY_ID_FAIL = "GET_STATE_BY_ID_FAIL";

// Upload all documents
export const UPLOAD_ALL_DOCUMENTS_STATE = "UPLOAD_ALL_DOCUMENTS_STATE";
export const UPLOAD_ALL_DOCUMENTS_STATE_SUCCESS =
  "UPLOAD_ALL_DOCUMENTS_STATE_SUCCESS";
export const UPLOAD_ALL_DOCUMENTS_STATE_FAIL =
  "UPLOAD_ALL_DOCUMENTS_STATE_FAIL";

//To set API response status
export const CREATE_EDIT_API_STATUS = "CREATE_EDIT_API_STATUS";
