export const FETCH_LOT_SERIES_REQUEST = 'FETCH_LOT_SERIES_REQUEST';
export const FETCH_LOT_SERIES_SUCCESS = 'FETCH_LOT_SERIES_SUCCESS';
export const FETCH_LOT_SERIES_FAILURE = 'FETCH_LOT_SERIES_FAILURE';



export const FETCH_LOT_SERIES_BY_ID_REQUEST = 'FETCH_LOT_SERIES_BY_ID_REQUEST';
export const FETCH_LOT_SERIES_BY_ID_SUCCESS = 'FETCH_LOT_SERIES_BY_ID_SUCCESS';
export const FETCH_LOT_SERIES_BY_ID_FAILURE = 'FETCH_LOT_SERIES_BY_ID_FAILURE';



export const ADD_LOT_SERIES_REQUEST = 'ADD_LOT_SERIES_REQUEST';
export const ADD_LOT_SERIES_SUCCESS = 'ADD_LOT_SERIES_SUCCESS';
export const ADD_LOT_SERIES_FAILURE = 'ADD_LOT_SERIES_FAILURE';



export const UPDATE_LOT_SERIES_REQUEST = 'UPDATE_LOT_SERIES_REQUEST';
export const UPDATE_LOT_SERIES_SUCCESS = 'UPDATE_LOT_SERIES_SUCCESS';
export const UPDATE_LOT_SERIES_FAILURE = 'UPDATE_LOT_SERIES_FAILURE';



export const DELETE_LOT_SERIES_REQUEST = 'DELETE_LOT_SERIES_REQUEST';
export const DELETE_LOT_SERIES_SUCCESS = 'DELETE_LOT_SERIES_SUCCESS';
export const DELETE_LOT_SERIES_FAILURE = 'DELETE_LOT_SERIES_FAILURE';